// @generated by
//     __             _____     _                 ___ ___ 
//  _ |  |___ ___ ___|   __|___| |_ ___ _____  __| | |_  |
// | |_| |_ -| . |   |__   |  _|   | -_|     ||. |_  |  _|
// |_____|___|___|_|_|_____|___|_|_|___|_|_|_|___| |_|___|
//                                 -- www.JsonSchema42.org

/* eslint-disable */
/* spellchecker: disable */

export type Core = ({
    $id?: CoreId;
    $schema?: CoreSchema;
    $ref?: CoreRef;
    $anchor?: CoreAnchor;
    $dynamicRef?: CoreDynamicRef;
    $dynamicAnchor?: CoreDynamicAnchor;
    $vocabulary?: CoreVocabulary;
    $comment?: CoreComment;
    $defs?: CoreDefs;
} | boolean);
export type CoreAnchorString = (string);
export type CoreUriString = (string);
export type CoreUriReferenceString = (string);
export type CoreId = CoreUriReferenceString;
export type CoreSchema = CoreUriString;
export type CoreRef = CoreUriReferenceString;
export type CoreAnchor = CoreAnchorString;
export type CoreDynamicRef = CoreUriReferenceString;
export type CoreDynamicAnchor = CoreAnchorString;
export type CoreVocabulary = (Record<string, CoreVocabularyAdditionalProperties>);
export type CoreComment = (string);
export type CoreDefs = (Record<string, CoreDefsAdditionalProperties>);
export type CoreVocabularyAdditionalProperties = (boolean);
export type CoreDefsAdditionalProperties = Schema;
export type Applicator = ({
    prefixItems?: ApplicatorPrefixItems;
    items?: ApplicatorItems;
    contains?: ApplicatorContains;
    additionalProperties?: ApplicatorAdditionalProperties;
    properties?: ApplicatorProperties;
    patternProperties?: ApplicatorPatternProperties;
    dependentSchemas?: ApplicatorDependentSchemas;
    propertyNames?: ApplicatorPropertyNames;
    if?: ApplicatorIf;
    then?: ApplicatorThen;
    else?: ApplicatorElse;
    allOf?: ApplicatorAllOf;
    anyOf?: ApplicatorAnyOf;
    oneOf?: ApplicatorOneOf;
    not?: ApplicatorNot;
} | boolean);
export type ApplicatorSchemaArray = (ApplicatorSchemaArrayItems[]);
export type ApplicatorPrefixItems = ApplicatorSchemaArray;
export type ApplicatorItems = Schema;
export type ApplicatorContains = Schema;
export type ApplicatorAdditionalProperties = Schema;
export type ApplicatorProperties = (Record<string, ApplicatorPropertiesAdditionalProperties>);
export type ApplicatorPatternProperties = (Record<string, ApplicatorPatternPropertiesAdditionalProperties>);
export type ApplicatorDependentSchemas = (Record<string, ApplicatorDependentSchemasAdditionalProperties>);
export type ApplicatorPropertyNames = Schema;
export type ApplicatorIf = Schema;
export type ApplicatorThen = Schema;
export type ApplicatorElse = Schema;
export type ApplicatorAllOf = ApplicatorSchemaArray;
export type ApplicatorAnyOf = ApplicatorSchemaArray;
export type ApplicatorOneOf = ApplicatorSchemaArray;
export type ApplicatorNot = Schema;
export type ApplicatorSchemaArrayItems = Schema;
export type ApplicatorPropertiesAdditionalProperties = Schema;
export type ApplicatorPatternPropertiesAdditionalProperties = Schema;
export type ApplicatorDependentSchemasAdditionalProperties = Schema;
export type Unevaluated = ({
    unevaluatedItems?: UnevaluatedUnevaluatedItems;
    unevaluatedProperties?: UnevaluatedUnevaluatedProperties;
} | boolean);
export type UnevaluatedUnevaluatedItems = Schema;
export type UnevaluatedUnevaluatedProperties = Schema;
export type Validation = ({
    type?: ValidationType;
    const?: ValidationConst;
    enum?: ValidationEnum;
    multipleOf?: ValidationMultipleOf;
    maximum?: ValidationMaximum;
    exclusiveMaximum?: ValidationExclusiveMaximum;
    minimum?: ValidationMinimum;
    exclusiveMinimum?: ValidationExclusiveMinimum;
    maxLength?: ValidationMaxLength;
    minLength?: ValidationMinLength;
    pattern?: ValidationPattern;
    maxItems?: ValidationMaxItems;
    minItems?: ValidationMinItems;
    uniqueItems?: ValidationUniqueItems;
    maxContains?: ValidationMaxContains;
    minContains?: ValidationMinContains;
    maxProperties?: ValidationMaxProperties;
    minProperties?: ValidationMinProperties;
    required?: ValidationRequired;
    dependentRequired?: ValidationDependentRequired;
} | boolean);
export type ValidationNonNegativeInteger = (number);
export type ValidationNonNegativeIntegerDefault0 = ValidationNonNegativeInteger;
export type ValidationSimpleTypes = unknown;
export type ValidationStringArray = (ValidationStringArrayItems[]);
export type ValidationType = ((Partial<ValidationType0> & Partial<ValidationType1>));
export type ValidationConst = (any);
export type ValidationEnum = (ValidationEnumItems[]);
export type ValidationMultipleOf = (number);
export type ValidationMaximum = (number);
export type ValidationExclusiveMaximum = (number);
export type ValidationMinimum = (number);
export type ValidationExclusiveMinimum = (number);
export type ValidationMaxLength = ValidationNonNegativeInteger;
export type ValidationMinLength = ValidationNonNegativeIntegerDefault0;
export type ValidationPattern = (string);
export type ValidationMaxItems = ValidationNonNegativeInteger;
export type ValidationMinItems = ValidationNonNegativeIntegerDefault0;
export type ValidationUniqueItems = (boolean);
export type ValidationMaxContains = ValidationNonNegativeInteger;
export type ValidationMinContains = ValidationNonNegativeInteger;
export type ValidationMaxProperties = ValidationNonNegativeInteger;
export type ValidationMinProperties = ValidationNonNegativeIntegerDefault0;
export type ValidationRequired = ValidationStringArray;
export type ValidationDependentRequired = (Record<string, ValidationDependentRequiredAdditionalProperties>);
export type ValidationStringArrayItems = (string);
export type ValidationType0 = ValidationSimpleTypes;
export type ValidationType1 = (ValidationType1Items[]);
export type ValidationType1Items = ValidationSimpleTypes;
export type ValidationEnumItems = (any);
export type ValidationDependentRequiredAdditionalProperties = ValidationStringArray;
export type MetaData = ({
    title?: MetaDataTitle;
    description?: MetaDataDescription;
    default?: MetaDataDefault;
    deprecated?: MetaDataDeprecated;
    readOnly?: MetaDataReadOnly;
    writeOnly?: MetaDataWriteOnly;
    examples?: MetaDataExamples;
} | boolean);
export type MetaDataTitle = (string);
export type MetaDataDescription = (string);
export type MetaDataDefault = (any);
export type MetaDataDeprecated = (boolean);
export type MetaDataReadOnly = (boolean);
export type MetaDataWriteOnly = (boolean);
export type MetaDataExamples = (MetaDataExamplesItems[]);
export type MetaDataExamplesItems = (any);
export type FormatAnnotation = ({
    format?: FormatAnnotationFormat;
} | boolean);
export type FormatAnnotationFormat = (string);
export type Content = ({
    contentEncoding?: ContentContentEncoding;
    contentMediaType?: ContentContentMediaType;
    contentSchema?: ContentContentSchema;
} | boolean);
export type ContentContentEncoding = (string);
export type ContentContentMediaType = (string);
export type ContentContentSchema = Schema;
export type Schema = (((Schema0 & Schema1 & Schema2 & Schema3 & Schema4 & Schema5 & Schema6)) & ({
    definitions?: SchemaDefinitions;
    dependencies?: SchemaDependencies;
    $recursiveAnchor?: SchemaRecursiveAnchor;
    $recursiveRef?: SchemaRecursiveRef;
} | boolean));
/**
@deprecated
*/
export type SchemaDefinitions = (Record<string, SchemaDefinitionsAdditionalProperties>);
/**
@deprecated
*/
export type SchemaDependencies = (Record<string, SchemaDependenciesAdditionalProperties>);
/**
@deprecated
*/
export type SchemaRecursiveAnchor = CoreAnchorString;
/**
@deprecated
*/
export type SchemaRecursiveRef = CoreUriReferenceString;
export type Schema0 = Core;
export type Schema1 = Applicator;
export type Schema2 = Unevaluated;
export type Schema3 = Validation;
export type Schema4 = MetaData;
export type Schema5 = FormatAnnotation;
export type Schema6 = Content;
export type SchemaDefinitionsAdditionalProperties = Schema;
export type SchemaDependenciesAdditionalProperties = ((Partial<SchemaDependenciesAdditionalProperties0> & Partial<SchemaDependenciesAdditionalProperties1>));
export type SchemaDependenciesAdditionalProperties0 = Schema;
export type SchemaDependenciesAdditionalProperties1 = ValidationStringArray;
